# Generated by Django 5.2.16 on 2026-09-28 21:24

import django.db.models.deletion
import sheets_reports.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre descriptivo del tablero.', max_length=255)),
                ('sheet_url', models.URLField(help_text='URL de la hoja de Google Sheets.', max_length=500)),
                ('sheet_gid', models.CharField(default='0', help_text="gid de la pestaña a leer (el número después de '#gid=' en la URL).", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(help_text='Usuario propietario del tablero.', on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dashboard',
                'verbose_name_plural': 'Dashboards',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('kpi', 'Tarjeta KPI'), ('bar', 'Gráfico de Barras'), ('line', 'Gráfico de Líneas'), ('donut', 'Gráfico de Dona'), ('table', 'Tabla')], max_length=10)),
                ('position', models.JSONField(default=sheets_reports.models.default_position, help_text='Posición en el lienzo: x = columna inicial (0 = fluido), y = orden, w = columnas (1-12), h = alto en px.')),
                ('data_spec', models.JSONField(help_text='Capa de datos: consulta (dimensiones, pivote, métricas, filtros, orden).')),
                ('view_spec', models.JSONField(help_text='Capa de presentación, derivada de data_spec + type.')),
                ('source_prompt', models.TextField(blank=True, help_text='Prompt original del usuario, si se generó con IA.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='sheets_reports.dashboard')),
            ],
            options={
                'verbose_name': 'Widget',
                'verbose_name_plural': 'Widgets',
                'ordering': ['created_at'],
            },
        ),
    ]
