# Generated by Django 5.2.16 on 2026-10-04 12:09

import sheets_reports.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets_reports', '0006_data_spec_own_keys'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='widget',
            name='data_spec',
        ),
        migrations.RemoveField(
            model_name='widget',
            name='view_spec',
        ),
        migrations.AddField(
            model_name='widget',
            name='fields',
            field=models.JSONField(default=dict, help_text='Campos de datos (dimensions, metrics, filters, etc.)'),
        ),
        migrations.AddField(
            model_name='widget',
            name='style',
            field=models.JSONField(default=dict, help_text='Opciones estéticas según el style_schema'),
        ),
        migrations.AddField(
            model_name='widget',
            name='title',
            field=models.CharField(default='Nuevo Widget', max_length=255),
        ),
        migrations.AlterField(
            model_name='widget',
            name='type',
            field=models.CharField(choices=sheets_reports.models.widget_type_choices, max_length=50),
        ),
    ]
