# Generated by Django 5.2.16 on 2026-10-06 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets_reports', '0008_create_cache_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='columns',
            field=models.JSONField(blank=True, default=list, help_text='Columnas elegidas al conectar la hoja: [{"name", "type": "text"|"number"|"date", "include"}]. Vacío = todas, con el tipo que trae la hoja.'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='last_opened_at',
            field=models.DateTimeField(blank=True, help_text='Última vez que se abrió en el editor.', null=True),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='sheet_name',
            field=models.CharField(blank=True, default='', help_text='Nombre del documento de Google Sheets.', max_length=255),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='tab_name',
            field=models.CharField(blank=True, default='', help_text='Nombre de la pestaña.', max_length=255),
        ),
    ]
