# Generated by Django 5.2.16 on 2026-10-06 21:34

import re

import django.db.models.deletion
from django.db import migrations, models


def sheets_to_sources(apps, schema_editor):
    """La hoja de cada tablero pasa a ser su primera fuente, y sus widgets la usan."""
    Dashboard = apps.get_model("sheets_reports", "Dashboard")
    DataSource = apps.get_model("sheets_reports", "DataSource")
    Widget = apps.get_model("sheets_reports", "Widget")
    for dashboard in Dashboard.objects.all():
        m = re.search(r"/spreadsheets/d/([a-zA-Z0-9_-]+)", dashboard.sheet_url or "")
        source = DataSource.objects.create(
            dashboard=dashboard,
            sheet_id=m.group(1) if m else "",
            gid=dashboard.sheet_gid or "0",
            sheet_name=dashboard.sheet_name,
            tab_name=dashboard.tab_name,
            columns=dashboard.columns or [],
        )
        Widget.objects.filter(dashboard=dashboard).update(source=source)


class Migration(migrations.Migration):

    dependencies = [
        ('sheets_reports', '0009_dashboard_source_columns'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('google_sheet', 'Hoja de Google')], default='google_sheet', max_length=30)),
                ('sheet_id', models.CharField(help_text='Id del documento de Google Sheets.', max_length=200)),
                ('gid', models.CharField(default='0', help_text='gid de la pestaña.', max_length=50)),
                ('sheet_name', models.CharField(blank=True, default='', help_text='Nombre del documento.', max_length=255)),
                ('tab_name', models.CharField(blank=True, default='', help_text='Nombre de la pestaña.', max_length=255)),
                ('columns', models.JSONField(blank=True, default=list, help_text='Columnas elegidas al conectar la hoja: [{"name", "type": "text"|"number"|"date", "include"}]. Vacío = todas, con el tipo que trae la hoja.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='sheets_reports.dashboard')),
            ],
            options={
                'verbose_name': 'Fuente de datos',
                'verbose_name_plural': 'Fuentes de datos',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='widget',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='widgets', to='sheets_reports.datasource'),
        ),
        migrations.RunPython(sheets_to_sources, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='dashboard',
            name='columns',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='sheet_gid',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='sheet_name',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='sheet_url',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='tab_name',
        ),
    ]
