# Generated by Django 5.2.16 on 2026-10-07 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets_reports', '0010_data_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='first_row_headers',
            field=models.BooleanField(default=True, help_text='La primera fila de la pestaña son los encabezados de las columnas.'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='name',
            field=models.CharField(blank=True, default='', help_text='Nombre opcional de la fuente; vacío = «Documento · Pestaña».', max_length=255),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='columns',
            field=models.JSONField(blank=True, default=list, help_text='Columnas elegidas al conectar la hoja: [{"name", "label"?, "type": "text"|"number"|"date", "include"}]. `name` es el encabezado de la hoja y `label`, el nombre a mostrar que lo reemplaza en todo el tablero. Vacío = todas, con el tipo que trae la hoja.'),
        ),
    ]
