# Generated by Django 5.2.16 on 2026-10-07 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets_reports', '0011_data_source_name_headers'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='calculated_fields',
            field=models.JSONField(blank=True, default=list, help_text='Campos calculados: [{"id", "name", "formula", "format": "number"|"percent"}]. Sin agregaciones son por fila (una columna más); con SUM, AVG… son agregados (solo métricas). Ver engine/formulas.py.'),
        ),
    ]
