# Generated by Django 5.2.16 on 2026-10-09 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets_reports', '0014_create_sheet_cache_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='is_form_response',
            field=models.BooleanField(default=False, help_text='La pestaña es una hoja de respuestas de Google Forms: se lee en modelo tidy (una fila por opción seleccionada, con «Pregunta | Aspecto | Respuesta»). Ver services/form_tidy.py.'),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='columns',
            field=models.JSONField(blank=True, default=list, help_text='Columnas elegidas al conectar la hoja: [{"name", "label"?, "type": "text"|"number"|"date", "include", "question_type"?}]. `name` es el encabezado de la hoja, `label` el nombre a mostrar que lo reemplaza en todo el tablero, y `question_type` su clasificación en respuestas de formulario (SCALAR|CHECKBOX|GRID|CHECKBOX_GRID|FREE_TEXT_WITH_COMMAS). Vacío = todas, con el tipo que trae la hoja.'),
        ),
    ]
