# Generated by Django 5.2.16 on 2026-10-10 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets_reports', '0015_datasource_is_form_response_alter_datasource_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='columns',
            field=models.JSONField(blank=True, default=list, help_text='Columnas elegidas al conectar la hoja: [{"name", "label"?, "type": "text"|"number"|"date", "include"}]. `name` es el encabezado (o columna del modelo tidy, en respuestas de formulario), `label` el nombre a mostrar que lo reemplaza en todo el tablero. Vacío = todas, con el tipo que trae la hoja.'),
        ),
    ]
