"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from decouple import config
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-1wxzuep7z&cicduh43b0g+n@u4%s)^r&ma$fasvbzno&$9q=-j')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config(
    'ALLOWED_HOSTS',
    default='',
    cast=lambda v: [h.strip() for h in v.split(',') if h.strip()]
)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'sheets_reports',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        # Si no encuentra DATABASE_URL en el entorno, usa SQLite local por defecto
        default=config('DATABASE_URL', default=f"sqlite:///{BASE_DIR / 'db.tableia.sqlite3'}"),
        conn_max_age=600,
        ssl_require=False
    )
}

# Caché compartida entre workers (Gunicorn corre varios procesos en producción).
# Respaldada en la misma base de datos: sin esto, Django usa por defecto
# LocMemCache (memoria local a cada proceso) y cada worker leería la hoja de
# Google Sheets por su cuenta (ver sheets_reports/services/sheets.py).
# La tabla la crea `migrate` (sheets_reports/migrations/0008_create_cache_table.py).
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'django_cache_table',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

# Prefijo bajo el cual corre la app en producción (ej. detrás de un Apache
# Alias /sheets-reports). Vacío en desarrollo. Django lo antepone automáticamente
# a las URLs generadas con {% url %} / reverse() y a STATIC_URL; para que el JS
# del frontend (fetch a /api/...) también lo respete, se expone como
# window.SCRIPT_NAME en base.html.
REPORT_PATH = config('REPORT_PATH', default='')
FORCE_SCRIPT_NAME = REPORT_PATH or None
STATIC_URL = f'{REPORT_PATH}/static/'

# Carpeta donde `collectstatic` reúne todos los estáticos para producción.
STATIC_ROOT = BASE_DIR / 'staticfiles'

# `{% static %}` añade la versión del archivo (?v=<mtime>): un JS cambiado nunca sale de caché.
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {"BACKEND": "sheets_reports.storage.VersionedStaticFilesStorage"},
}

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Google Sheets
GOOGLE_SHEETS_CREDENTIALS_PATH = config("GOOGLE_SHEETS_CREDENTIALS_PATH", default="")

# Segundos que se cachea el DataFrame de cada hoja (services/sheets.get_sheet_dataframe).
SHEET_CACHE_TTL = config("SHEET_CACHE_TTL", default=300, cast=int)

# Cada cuántos minutos el frontend refresca los datos del tablero (endpoint render, sin IA).
WIDGET_REFRESH_MINUTES = config("WIDGET_REFRESH_MINUTES", default=5, cast=int)

# Gemini (generación de specs JSON de widgets vía IA; ver services/ai_spec.py)
GEMINI_API_KEY = config("GEMINI_API_KEY", default="")
GEMINI_MODEL = config("GEMINI_MODEL", default="gemini-2.5-flash")

# Auditoría de cada spec generado por IA junto al prompt que lo originó (logger
# "tableia.ai_audit"), para revisar y mejorar el system prompt con el tiempo.
AI_AUDIT_LOG_FILE = config("AI_AUDIT_LOG_FILE", default="") or str(BASE_DIR / "ai_audit.log")

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "audit": {"format": "%(asctime)s %(message)s"},
    },
    "handlers": {
        "console": {"class": "logging.StreamHandler"},
        "ai_audit_file": {
            "class": "logging.handlers.WatchedFileHandler",
            "filename": AI_AUDIT_LOG_FILE,
            "formatter": "audit",
            "encoding": "utf-8",
        },
    },
    "loggers": {
        "tableia.ai_audit": {"handlers": ["ai_audit_file"], "level": "INFO", "propagate": False},
    },
    "root": {"handlers": ["console"], "level": "WARNING"},
}

# Configuración para GUNICON - APACHE
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
